# Implementation of Simple ML Model - 20MAI0015

In [1]:

from sklearn.datasets import * # importing all the datasets


C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:

import numpy as np # importing numpy and aliasing it as np for ease of use


In [3]:

import pandas as pd # importing pandas and aliasing it as pd for easy of use


C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:

cancer_ds = sklearn.datasets.load_breast_cancer()# error due to the miss of import statement in sklearn


NameError: name 'sklearn' is not defined

In [7]:

import sklearn # importing inbuilt function sklearn


In [9]:

from sklearn.datasets import * # importing thee daatasets


In [10]:

cancer_ds = sklearn.datasets.load_breast_cancer()


# variable assignment of data and target variables

In [11]:

X = cancer_ds.data
Y = cancer_ds.target


# for viewing purpose we are printing the values of x and y

In [13]:

print(X)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [14]:

len (X)


569

In [15]:

print(Y)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [16]:

len (Y)


569

In [17]:

# to know the shape of X and Y we are are printing the below line
print(X.shape,Y.shape)


(569, 30) (569,)


In [101]:

#x-> is of 569 elements and inside the 569 elements in array there are 
#    furthermore 30 individual elements present inside the 569 data items
#y-> is of one list of 's and 1's of 569 items


# putting the data into a pandas dataframe

In [23]:

data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names)


In [24]:

#creating a feild class in the dataframe itself aas class
data['class'] = cancer_ds.target


In [25]:


#to view the change took place in the data frme or not
data.head()# this will display the first five rows of the dataframe



mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [26]:


#Count number of non-NA/null observations.
#Maximum of the values in the object.
#Minimum of the values in the object.
#Mean of the values.
#Standard deviation of the observations.
#Subset of a DataFrame including/excluding columns based on their dtype.
data.describe()



mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [27]:

#how many malignant and bengin?
data['class'].value_counts()#binary variablle


1    357
0    212
Name: class, dtype: int64

In [28]:

#know the target names
print(cancer_ds.target_names)#only 2 are there


['malignant' 'benign']


In [29]:

#we are using group by to group of 0's and 1's and we are grouping by mean
data.groupby('class').mean()


mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

In [30]:

Train test and split
from sklearn.model_selection import train_test_split


In [31]:

Removing rows or columns by specifying label names and corresponding axis 'class' is removed in X
X = data.drop('class', axis=1)


In [34]:

#labeling the class
Y = data['class']


In [39]:
#variable assignment for further study
Q = X
W = Y
E = X
R = Y
A = X
B = Y
C = X
D = Y

In [48]:
#code to split
# experimenting the the data split and parameters associated with it such as test_size and random_state
X_train,X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.08, stratify = Y, random_state = 1)
# for random state analysis
Q_train,Q_test, W_train, W_test = train_test_split(Q,W,test_size = 0.08, stratify = W, random_state = 2)
E_train,E_test, R_train, R_test = train_test_split(E,R,test_size = 0.08, stratify = R, random_state = 10)
#for test and train value split analysis
A_train,A_test, B_train, B_test = train_test_split(A,B,test_size = 0.2, stratify = B, random_state = 1)
C_train,C_test, D_train, D_test = train_test_split(C,D,test_size = 0.1, stratify = D, random_state = 1)

In [49]:
# analysing the shapes of X and Y and mean values
print(X.shape,X_train.shape,X_test.shape)
print(Y.shape,Y_train.shape,Y_test.shape)
print(X.mean(),X_train.mean(),X_test.mean())
print(Y.mean(),Y_train.mean(),Y_test.mean())





(569, 30) (523, 30) (46, 30)
(569,) (523,) (46,)
mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
w

In [50]:
#experimental purpose
print(Q.shape,Q_train.shape,Q_test.shape)
print(E.shape,E_train.shape,E_test.shape)
print(A.shape,A_train.shape,A_test.shape)
print(C.shape,C_train.shape,C_test.shape)

(569, 30) (523, 30) (46, 30)
(569, 30) (523, 30) (46, 30)
(569, 30) (455, 30) (114, 30)
(569, 30) (512, 30) (57, 30)


In [51]:
#experimental purpose
print(W.shape,W_train.shape,W_test.shape)
print(R.shape,R_train.shape,R_test.shape)
print(B.shape,B_train.shape,B_test.shape)
print(D.shape,D_train.shape,D_test.shape)

(569,) (523,) (46,)
(569,) (523,) (46,)
(569,) (455,) (114,)
(569,) (512,) (57,)


In [52]:
#experimental purpose
print(W.mean(),W_train.mean(),W_test.mean())
print(R.mean(),R_train.mean(),R_test.mean())
print(B.mean(),B_train.mean(),B_test.mean())
print(D.mean(),D_train.mean(),D_test.mean())

0.6274165202108963 0.627151051625239 0.6304347826086957
0.6274165202108963 0.627151051625239 0.6304347826086957
0.6274165202108963 0.6263736263736264 0.631578947368421
0.6274165202108963 0.626953125 0.631578947368421


In [53]:


#mean values of Q train and test
print(Q.mean(),Q_train.mean(),Q_test.mean())# for random state analysis



mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [54]:


#mean values of E train and test
print(E.mean(),E_train.mean(),E_test.mean())# for random state analysis



mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [55]:


#mean values of A train and test
print(A.mean(),A_train.mean(),A_test.mean())



mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [56]:


#mean values of C train and test
print(C.mean(),C_train.mean(),C_test.mean())



mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [57]:


# Binarization of input X and Y
X_binarised_train = X_train.apply(pd.cut,bins=2, labels=[1,0])
X_binarised_test = X_test.apply(pd.cut,bins=2, labels=[1,0])
type(X_binarised_train)
X_binarised_train = X_binarised_train.values
X_binarised_test = X_binarised_test.values



In [58]:
#possible values that b can take
b = 10#possible values 0 - 30
from random import randint
i = randint(0 , X_binarised_train.shape[0])
if(np.sum(X_binarised_train[i,:])>=b):
    print("Model prediction is Malignant")
else:
    print("Model prediction is bengin")   
if (Y_train[i]==1):
    print("Actual prediction is Malignant")
else:
    print("Actual prediction is bengin")

Model prediction is Malignant
Actual prediction is bengin


In [75]:


#building the model and training it
##b = 10
for b in range(X_binarised_train.shape[1]+1):
    accurate_rows = 0
    for x,y in zip(X_binarised_train,Y_train):
        y_pred = (np.sum(x)>=b)
        accurate_rows +=(y == y_pred)
    print("for b = ",b,accurate_rows,accurate_rows/X_binarised_train.shape[0])
    
    

for b =  0 328 0.627151051625239
for b =  1 328 0.627151051625239
for b =  2 328 0.627151051625239
for b =  3 328 0.627151051625239
for b =  4 328 0.627151051625239
for b =  5 328 0.627151051625239
for b =  6 328 0.627151051625239
for b =  7 328 0.627151051625239
for b =  8 328 0.627151051625239
for b =  9 328 0.627151051625239
for b =  10 328 0.627151051625239
for b =  11 328 0.627151051625239
for b =  12 328 0.627151051625239
for b =  13 329 0.6290630975143403
for b =  14 330 0.6309751434034416
for b =  15 331 0.6328871892925431
for b =  16 336 0.6424474187380497
for b =  17 339 0.6481835564053537
for b =  18 343 0.655831739961759
for b =  19 346 0.6615678776290631
for b =  20 351 0.6711281070745698
for b =  21 361 0.6902485659655831
for b =  22 370 0.7074569789674953
for b =  23 383 0.7323135755258127
for b =  24 398 0.7609942638623327
for b =  25 416 0.7954110898661568
for b =  26 432 0.8260038240917782
for b =  27 444 0.8489483747609943
for b =  28 444 0.8489483747609943
for b =  

In [77]:



# taking the b value in the test data as we found 28 and 27 to be best accurate in the training.
b = 28
accurate_rows=0
for x,y in zip(X_binarised_test,Y_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
    print("for b = ",b,accurate_rows,accurate_rows/X_binarised_test.shape[0])
    
    
    


for b =  28 0 0.0
for b =  28 1 0.021739130434782608
for b =  28 2 0.043478260869565216
for b =  28 3 0.06521739130434782
for b =  28 4 0.08695652173913043
for b =  28 5 0.10869565217391304
for b =  28 6 0.13043478260869565
for b =  28 7 0.15217391304347827
for b =  28 8 0.17391304347826086
for b =  28 8 0.17391304347826086
for b =  28 9 0.1956521739130435
for b =  28 9 0.1956521739130435
for b =  28 10 0.21739130434782608
for b =  28 10 0.21739130434782608
for b =  28 11 0.2391304347826087
for b =  28 12 0.2608695652173913
for b =  28 13 0.2826086956521739
for b =  28 14 0.30434782608695654
for b =  28 15 0.32608695652173914
for b =  28 16 0.34782608695652173
for b =  28 17 0.3695652173913043
for b =  28 18 0.391304347826087
for b =  28 19 0.41304347826086957
for b =  28 19 0.41304347826086957
for b =  28 20 0.43478260869565216
for b =  28 21 0.45652173913043476
for b =  28 22 0.4782608695652174
for b =  28 22 0.4782608695652174
for b =  28 23 0.5
for b =  28 24 0.5217391304347826
for

In [78]:


# finding values for 27 and 28 condensing the output to two lies
b = 27
accurate_rows=0
for x,y in zip(X_binarised_test,Y_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
print("for b = ",b,accurate_rows,accurate_rows/X_binarised_test.shape[0])
b = 28
accurate_rows=0
for x,y in zip(X_binarised_test,Y_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
print("for b = ",b,accurate_rows,accurate_rows/X_binarised_test.shape[0])



for b =  27 39 0.8478260869565217
for b =  28 37 0.8043478260869565


# Conclusion

In [79]:


# in the training data we found 27 and 28 to have best accuracy
# so in the test data we took 27 and 28 and obtained a better accuracy of 84.78% and 80.43% respectively 


# Experiment continues

# for A and B values

In [80]:



# Binarization of input A and B
A_binarised_train = A_train.apply(pd.cut,bins=2, labels=[1,0])
A_binarised_test = A_test.apply(pd.cut,bins=2, labels=[1,0])
type(A_binarised_train)
A_binarised_train = A_binarised_train.values
A_binarised_test = A_binarised_test.values

In [81]:
#building the model and training it
for b in range(A_binarised_train.shape[1]+1):
    accurate_rows = 0
    for x,y in zip(A_binarised_train,B_train):
        y_pred = (np.sum(x)>=b)
        accurate_rows +=(y == y_pred)
    print("for b = ",b,accurate_rows,accurate_rows/A_binarised_train.shape[0])

for b =  0 285 0.6263736263736264
for b =  1 285 0.6263736263736264
for b =  2 285 0.6263736263736264
for b =  3 285 0.6263736263736264
for b =  4 285 0.6263736263736264
for b =  5 285 0.6263736263736264
for b =  6 285 0.6263736263736264
for b =  7 285 0.6263736263736264
for b =  8 285 0.6263736263736264
for b =  9 285 0.6263736263736264
for b =  10 285 0.6263736263736264
for b =  11 285 0.6263736263736264
for b =  12 285 0.6263736263736264
for b =  13 286 0.6285714285714286
for b =  14 287 0.6307692307692307
for b =  15 288 0.6329670329670329
for b =  16 293 0.643956043956044
for b =  17 296 0.6505494505494506
for b =  18 300 0.6593406593406593
for b =  19 304 0.6681318681318681
for b =  20 308 0.676923076923077
for b =  21 315 0.6923076923076923
for b =  22 320 0.7032967032967034
for b =  23 330 0.7252747252747253
for b =  24 343 0.7538461538461538
for b =  25 358 0.7868131868131868
for b =  26 371 0.8153846153846154
for b =  27 381 0.8373626373626374
for b =  28 385 0.84615384615384

In [82]:
#here the accuracy changes due to the variiation in split of training and tet data



In [92]:


# finding values for 27 and 28 condensing the output to two lies
b = 27
accurate_rows=0
for x,y in zip(A_binarised_test,B_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
print("for b = ",b,accurate_rows,(accurate_rows/A_binarised_test.shape[0])*100,"%")
b = 28
accurate_rows=0
for x,y in zip(A_binarised_test,B_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
print("for b = ",b,accurate_rows,(accurate_rows/A_binarised_test.shape[0])*100,"%")



for b =  27 96 84.21052631578947 %
for b =  28 89 78.0701754385965 %


# for C and D values

In [93]:


# Binarization of input C and D
C_binarised_train = C_train.apply(pd.cut,bins=2, labels=[1,0])
C_binarised_test = C_test.apply(pd.cut,bins=2, labels=[1,0])
type(C_binarised_train)
C_binarised_train = C_binarised_train.values
C_binarised_test = C_binarised_test.values



In [94]:


#building the model and training it
for b in range(C_binarised_train.shape[1]+1):
    accurate_rows = 0
    for x,y in zip(C_binarised_train,D_train):
        y_pred = (np.sum(x)>=b)
        accurate_rows +=(y == y_pred)
    print("for b = ",b,accurate_rows,accurate_rows/C_binarised_train.shape[0])
    
    

for b =  0 321 0.626953125
for b =  1 321 0.626953125
for b =  2 321 0.626953125
for b =  3 321 0.626953125
for b =  4 321 0.626953125
for b =  5 321 0.626953125
for b =  6 321 0.626953125
for b =  7 321 0.626953125
for b =  8 321 0.626953125
for b =  9 321 0.626953125
for b =  10 321 0.626953125
for b =  11 321 0.626953125
for b =  12 321 0.626953125
for b =  13 321 0.626953125
for b =  14 323 0.630859375
for b =  15 324 0.6328125
for b =  16 329 0.642578125
for b =  17 332 0.6484375
for b =  18 336 0.65625
for b =  19 340 0.6640625
for b =  20 344 0.671875
for b =  21 352 0.6875
for b =  22 359 0.701171875
for b =  23 371 0.724609375
for b =  24 387 0.755859375
for b =  25 402 0.78515625
for b =  26 419 0.818359375
for b =  27 433 0.845703125
for b =  28 435 0.849609375
for b =  29 417 0.814453125
for b =  30 389 0.759765625


In [95]:

#here the accuracy changes due to the variiation in split of training and tet data



In [97]:


#Here also finding values for 27 and 28 condensing the output to two lies
b = 27
accurate_rows=0
for x,y in zip(C_binarised_test,D_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
print("for b = ",b,accurate_rows,(accurate_rows/C_binarised_test.shape[0])*100,"%")
b = 28
accurate_rows=0
for x,y in zip(C_binarised_test,D_test):
    y_pred = (np.sum(x)>=b)
    accurate_rows +=(y == y_pred)
print("for b = ",b,accurate_rows,(accurate_rows/C_binarised_test.shape[0])*100,"%")



for b =  27 49 85.96491228070175 %
for b =  28 45 78.94736842105263 %


In [99]:

#the accuracy varies from the previous model due tto train and test data split variation



In [100]:

#Observation - the accuracy varies depending upon the split of training and test data.

